def on_button_pressed_a():
    pass
input.on_button_pressed(Button.A, on_button_pressed_a)

lol = game.create_sprite(0, 0)
lol2 = game.create_sprite(0, 1)
lol3 = game.create_sprite(0, 2)

def on_forever():
    music.play_tone(165, music.beat(BeatFraction.WHOLE))
    music.play_tone(196, music.beat(BeatFraction.WHOLE))
    music.play_tone(196, music.beat(BeatFraction.HALF))
    music.play_tone(196, music.beat(BeatFraction.EIGHTH))
    music.play_tone(131, music.beat(BeatFraction.DOUBLE))
    music.play_tone(131, music.beat(BeatFraction.WHOLE))
    music.play_tone(147, music.beat(BeatFraction.WHOLE))
    music.play_tone(165, music.beat(BeatFraction.WHOLE))
    music.play_tone(175, music.beat(BeatFraction.WHOLE))
    music.play_tone(196, music.beat(BeatFraction.WHOLE))
    music.play_tone(220, music.beat(BeatFraction.WHOLE))
    music.play_tone(147, music.beat(BeatFraction.DOUBLE))
    music.play_tone(147, music.beat(BeatFraction.WHOLE))
    music.play_tone(165, music.beat(BeatFraction.DOUBLE))
    music.play_tone(185, music.beat(BeatFraction.WHOLE))
    music.play_tone(185, music.beat(BeatFraction.HALF))
    music.play_tone(185, music.beat(BeatFraction.EIGHTH))
    music.play_tone(196, music.beat(BeatFraction.DOUBLE))
    music.play_tone(196, music.beat(BeatFraction.WHOLE))
    music.play_tone(220, music.beat(BeatFraction.WHOLE))
    music.play_tone(247, music.beat(BeatFraction.WHOLE))
    music.play_tone(247, music.beat(BeatFraction.WHOLE))
    music.play_tone(220, music.beat(BeatFraction.WHOLE))
    music.play_tone(220, music.beat(BeatFraction.WHOLE))
    music.play_tone(196, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    for index in range(2):
        music.play_tone(147, music.beat(BeatFraction.HALF))
        music.play_tone(165, music.beat(BeatFraction.HALF))
        music.play_tone(175, music.beat(BeatFraction.WHOLE))
        music.play_tone(175, music.beat(BeatFraction.HALF))
        music.play_tone(165, music.beat(BeatFraction.EIGHTH))
        music.play_tone(147, music.beat(BeatFraction.WHOLE))
        music.play_tone(165, music.beat(BeatFraction.HALF))
        music.play_tone(175, music.beat(BeatFraction.HALF))
        music.play_tone(196, music.beat(BeatFraction.WHOLE))
        music.play_tone(196, music.beat(BeatFraction.HALF))
        music.play_tone(175, music.beat(BeatFraction.EIGHTH))
        music.play_tone(165, music.beat(BeatFraction.EIGHTH))
        music.play_tone(175, music.beat(BeatFraction.HALF))
        music.play_tone(196, music.beat(BeatFraction.HALF))
        music.play_tone(220, music.beat(BeatFraction.WHOLE))
        music.play_tone(196, music.beat(BeatFraction.WHOLE))
        music.play_tone(175, music.beat(BeatFraction.WHOLE))
        music.play_tone(165, music.beat(BeatFraction.WHOLE))
        music.play_tone(147, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(131, music.beat(BeatFraction.BREVE))
    music.rest(music.beat(BeatFraction.WHOLE))
basic.forever(on_forever)

def on_forever2():
    lol.move(1)
    lol2.move(1)
    lol3.move(1)
    lol3.turn(Direction.RIGHT, 45)
    lol2.turn(Direction.RIGHT, 45)
    lol.turn(Direction.RIGHT, 45)
basic.forever(on_forever2)
